version: "3.13"
services:
  fpg-api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=8000 --reload
