name: Test SSH Connection to Raspberry Pi

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    name: Test SSH Connection
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PI_SSH_KEY }}

      - name: Test SSH and list files on Raspberry Pi
        run: |
          # Ensure we can connect to the Pi and verify the host key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.PI_HOST }} << 'EOF'
            ls
          EOF
