name: Run Pytests

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Pytests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env.test
        run: echo "${{ secrets.ENV_TEST_FILE }}" > .env.test

      - name: Run tests
        run: |
          ENV=test pytest --disable-warnings -q
