name: Run Pytests

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Pytests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env.test
        run: echo "${{ secrets.ENV_TEST_FILE }}" > .env

      - name: Run tests
        run: |
          pytest --tb=short --disable-warnings -v --maxfail=1 --junitxml=test-results.xml

      - if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: test-results.xml
          summary: true
          display-options: fEXIT
          title: "Test Results Toby's"
